### ISSUE TITLE
Model organism description

### ISSUE THREAD

**Issue by Midnighter** [MetabolicAtlas/standard-GEM#13]
> :red_square: Pick a repository description
The description must include the taxonomic classification in full.
Example: The consensus GEM for Saccharomyces cerevisiae

Maybe this belongs more in a guide on _how_ to construct models but it doesn't hurt to have it in description and model annotation:

* A recommendation to use (I suppose) NCBI taxonomy name **and ID**
* The reference genome used to construct the model

**Comment by mihai-sysbio** [comment]
I believe these 2 fields are meant to be part of the [Keywords section in the README](https://github.com/MetabolicAtlas/standard-GEM/blob/master/README.md#keywords). If you don't mind, I'll integrate those two bullet points there.

The `repository description` refers to the GitHub repository description, see screenshot below:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/23480589/90132360-562eab80-dd76-11ea-9d73-6870f9a5d36f.png">

Just to check, you'd suggest to add the ID and ref genome there?

**Comment by Midnighter** [comment]
Keywords are a great place, too, although somewhat limited since they don't allow spaces. I think the description is fine as you suggest. Most importantly, all three pieces of information (name, ID, reference genome) should be annotated in SBML.

**Comment by mihai-sysbio** [comment]
I'm hoping this issue is resolved, please reopen if otherwise.
