### ISSUE TITLE
Make the model used by both cobrapy and cobra toolbox?

### ISSUE THREAD

**Issue by hongzhonglu** [MetabolicAtlas/standard-GEM#16]
It is know some GEMs can only run on the cobra toolbox based on MATLAB, but it can't be read and used by another popular toolbox-cobrapy. Thus, it should make sure that the GEMs can be used by both MATLAB or cobrapy. Otherwise the test result should be given which toolbox can read and run the GEMs.

**Comment by edkerk** [comment]
As long as the model is valid SBML, should it then not work in both COBRA and cobrapy? What would be an example of when this fails?

**Comment by hongzhonglu** [comment]
I remember there is  a GEM, which can be read by COBRA toolbox, but can't be read by cobrapy. I need firstly read it using COBRA and export a new xml file. The new xml file then can be read by cobrapy. I will further test some examples and give you feedback later.

**Comment by draeger** [comment]
The advantage of using SBML as a standard file format for encoding GEMs is those valid models are agnostic of any particular software solution. We should better encourage modelers to ensure the validity of their SBML file to benefit from the ability to conduct a large variety of different analyses with the same model in several modeling tools, not limited to any particular software.

Tightly coupling a model to a specific software tool can face two severe problems:
1. Even very popular software has faced a situation where its development slows down or could not be maintained for some time. This process could lead to a situation where the software becomes outdated and the model possibly with it.
2. The software could also quickly evolve, and an older version that was able to run the model could become replaced by a newer version. If a model requires a particular version of a software tool, it might become difficult with time to run it on newer hardware or later operating systems.

For these reasons, storing a model in a valid SBML file is preferable. There are tools to check the validity of a model, such as the [SBML validator](http://sbml.org/Facilities/Validator/) or [MEMOTE](https://memote.io). Those can be even used as part of a continuous integration setup of model development and testing.

Please note that the [SBML Test Suite](https://github.com/sbmlteam/sbml-test-suite/tree/develop/cases) now includes constraint-based models, allowing software developers to assess if their software is compliant. Consequently, valid SBML models should run in any standard-compliant software.

**Comment by mihai-sysbio** [comment]
There is an `automated-validation` branch that relies on GH Actions to run different tests on latest releases of models that follow `standard-GEM`. I've just made a note there about SBML testing. Basic YAML testing [is in place](https://github.com/MetabolicAtlas/standard-GEM/blob/72b1d5792fca0a2b663b2feb0eb023aafb6c008a/gh_api.py#L61-L80), but it will take a while until the validation setup is nice and thorough. We should continue to add ideas for validations there.

**Comment by sulheim** [comment]
I am not sure how closely this relates to the issue, or even if it is still an issue with the latest versions of cobrapy and cobratoolbox, but I often encounter models with metabolite names that are read differently by these two softwares, usually the appended '_c' or [c] that denotes the compartment. Is there a best practice that is bulletproof for both softwares?

**Comment by Midnighter** [comment]
@sulheim both programs still convert identifiers upon reading models which is not ideal but also somewhat necessary because folks have taken to using identifiers that are not SBML compliant. In cobrapy, we have been discussing not changing the identifiers read from SBML at all but additionally providing a 'nice' identifier that users can work with most of the time. However, this is a long way down the development roadmap.

**Comment by mihai-sysbio** [comment]
@sulheim thanks for bringing up this issue regarding compartment abbreviations in metabolite names. Do you think there is a test case that can be added to the automatic validation that is part of standard-GEM?

**Comment by draeger** [comment]
If there is no issue with identifier overloading with semantic information yet, please let us create one and continue discussing compartment abbreviations as metabolite identifier suffixes in this different thread.

**Comment by mihai-sysbio** [comment]
Good idea @draeger . There is now a note in #9 about the metabolite identifier suffixes. I am now closing this issue, please reopen if needed.
