### ISSUE TITLE
Include genome (+ annotation)

### ISSUE THREAD

**Issue by edkerk** [MetabolicAtlas/standard-GEM#17]
As [raised](https://github.com/MetabolicAtlas/standard-GEM/issues/15#issuecomment-673551036) by @cshenry:

> One thing I would consider to be of utmost importance in such a site is to properly represent the genomes linked to the models. Ideally, I would prefer the see the site maintain its own internal compressed copies of GFF and FASTA files for genomes associated with any models stored there. People routinely use genome IDs… but these IDs go away or genes get recalled and it makes things difficult. I would argue a model is nearly useless without its associated genome, and finding the exact correct genome that should be mapped to a particular published model is one of my greatest pain points in trying to use these models in my own research. You could store protein sequences in the model, which would help, but without the genome, you’re still losing some provenance on where the protein came from.

Seems like a valid point. Not convinced about the compressed copy, I'm always happier to avoid binary files in git.

**Comment by Midnighter** [comment]
This goes a lot further than my intention with #13. Is there no stable genome identifier at all?

**Comment by cshenry** [comment]
Both kbase and Patric offer stable genome IDs. Other platforms may also do so. I think a stable id, if truly stable and truly accessible, would work fine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mihai-sysbio** [comment]
Following the pointers above from @cshenry (thank you), I have found only PATRIC and GenBank to have _publicly_ available genome identifiers; one can only get so far in KBase without having to log in. Personally, I do not consider any of these follow FAIR principles, but having a genome ID in the template is an improvement nevertheless.

**Comment by Midnighter** [comment]
What about assemblies at NCBI, for example, https://www.ncbi.nlm.nih.gov/assembly/GCF_000007565.2/ lists

```
GenBank assembly accession:
    GCA_000007565.2 (latest)
RefSeq assembly accession:
    GCF_000007565.2 (latest)
```

I would hope that those are stable?

**Comment by mihai-sysbio** [comment]
Good idea about RefSeq! Here is the [comparison](https://www.ncbi.nlm.nih.gov/books/NBK50679/#RefSeqFAQ.what_is_the_difference_between_1) to GenBank:
> The GenBank archival sequence database includes publicly available DNA sequences submitted from individual laboratories and large-scale sequencing projects. GenBank is part of the International Nucleotide Sequence Database Collaboration (INSDC) along with the European Nucleotide Archive and the DNA Data Bank of Japan (DDBJ). Submitted sequence data is exchanged daily between the three collaborators to achieve comprehensive worldwide coverage. As an archival database, GenBank can be very redundant for some loci. GenBank sequence records are owned by the original submitter and cannot be altered by a third party.
RefSeq sequences are not part of the INSDC but are derived from INSDC sequences to provide non-redundant curated data representing our current knowledge of known genes. Some records include sequence information gathered from more than one INSDC record. Records may include sequence, descriptive information, publications, or feature annotation that is not available from any single INSDC record. RefSeq records are owned by NCBI and therefore can be updated as needed to maintain current annotation or to incorporate additional information. Also see the appendix provided in the NCBI Handbook, GenBank chapter.
Another distinction is that transcripts and proteins annotated on RefSeq genomic records are instantiated as separate records; in contrast, GenBank only instantiates the proteins annotated on genomic sequence records.

Moreover, RefSeq has an [identifiers.org profile](https://registry.identifiers.org/registry/refseq) which makes the compact identifier both human readable and useful (eg `refseq:NP_012345`).

**Comment by mihai-sysbio** [comment]
race condition over there with the edits :) 
[`insdc.gca:GCF_000007565.2`](https://identifiers.org/insdc.gca:GCF_000007565.2) seems to work nicely

**Comment by mihai-sysbio** [comment]
I believe this issue is resolved in the linked PRs - please reopen this issue if needed.
