### ISSUE TITLE
automated validation

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/standard-GEM#9]
This repository contains a branch (for) [`automated-validation`](https://github.com/MetabolicAtlas/standard-GEM/tree/automated-validation). In short, the aim of that branch is to use GitHub Actions to validate _all public repositories_ that follow `standard-GEM` and output a machine-readable file with the results, eg which version of the GEM follows which standard, `MEMOTE` results, `cobrapy` testing.
Documentation of the most up-to-date implementation is on the [wiki](https://github.com/MetabolicAtlas/standard-GEM/wiki/Automated-validation).
Ideas and feedback are welcome!

edit: This could be implemented with eg [Toil](https://toil.readthedocs.io/en/latest/gettingStarted/quickStart.html#running-a-basic-workflow).

**Comment by Hao-Chalmers** [comment]
Very good idea.

Based on the previously implemented PR [#173](https://github.com/SysBioChalmers/Human-GEM/pull/173) in `HumanGEM`, following checks may be included:
1. `yamllint`
2. `cobrapy` import

**Comment by mihai-sysbio** [comment]
There has been some progress on this. The suggestions from @Hao-Chalmers are already implemented as workflow with GitHub Actions in the `automated-validation` branch, with results being automatically committed to that same branch in the [results folder](https://github.com/MetabolicAtlas/standard-GEM/tree/automated-validation/results).
It looks like GitHub can schedule workflows only if they are available on the default branch (master), so it might be that the contents of the `automated-validation` branch would have to be moved to a separate repo.

**Comment by mihai-sysbio** [comment]
As mentioned in #16, the SBML fle should be tested with MEMOTE.

**Comment by mihai-sysbio** [comment]
As mentioned in #13, the SBML should contain taxonomy name, taxonomy ID, and reference genome.

**Comment by mihai-sysbio** [comment]
From the continued discussion in #16: perhaps one can devise a test to check the compatibility of `compartment abbreviations as metabolite identifier suffixes` in cobrapy and cobratoolbox.

**Comment by draeger** [comment]
I opened a separate discussion on the topic of identifiers and semantic overloading at https://github.com/MetabolicAtlas/standard-GEM/issues/27.

**Comment by mihai-sysbio** [comment]
For a clearer separation of concerns, the automated validation work has been promoted to a separate repository called [standard-GEM-validation](https://github.com/MetabolicAtlas/standard-GEM-validation/). The action points from this issue have been migrated to the new repository as distinct issues.
Since all future work will be carried out in that repository, this issue will be closed.
